---
name: pod-mode
abstract: Emacs syntax highlighting for POD
version: 1.01
author:
  - Steffen Schwigon <ss5@renormalist.net>
  - Florian Ragwitz <rafl@debian.org>
license: gpl_2
distribution_type: script
resources:
  license: http://dev.perl.org/licenses/
  homepage: http://renormalist.net/Renormalist/PodMode
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Steffen Schwigon
provides:
  pod-mode:
    file: pod-mode.el
    abstract: Emacs syntax highlighting for POD
    version: 1.01
